### ISSUE TITLE
Unable to set it up with nx react monorepo and bare react native project

### ISSUE THREAD

**Issue by quicksilverr** [xiongemi/nx-expo-poetry#5]
Hey @xiongemi ,

I have a nx monorepo, with bare react native project. I have configured my project with the neccessary expo documentations.

Eas update works, but eas build is failing. get this message always, please can you tell how to set it up?

getting this error - 

```
cript 'eas-build-pre-install' is present in package.json, running it...

> mobile-app@0.0.1 eas-build-pre-install

> cd ../../ && node tools/scripts/eas-build-pre-install.mjs . apps/mobile-app && cp yarn.lock apps/mobile-app

node:internal/modules/cjs/loader:988

  throw err;

  ^


Error: Cannot find module '/home/expo/workingdir/build/tools/scripts/eas-build-pre-install.mjs'

    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)

    at Function.Module._load (node:internal/modules/cjs/loader:833:27)

    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

    at node:internal/main/run_main_module:22:47 {

  code: 'MODULE_NOT_FOUND',

  requireStack: []

}
```

**Comment by xiongemi** [comment]
@quicksilverr in your repo, does `/home/expo/workingdir/build/tools/scripts/eas-build-pre-install.mjs` file exist?
is your workspace root `/home/expo/workingdir` or `/home/expo/workingdir/build`?

**Comment by xiongemi** [comment]
@quicksilverr do you have a repo that i could look at?

**Comment by quicksilverr** [comment]
Hey Xiongemi, home/expo/workingdir/build/tools/scripts/eas-build-pre-install.mjs is the filepath, that comes from the error logs of the expo build on their website.

**Comment by quicksilverr** [comment]
> @quicksilverr do you have a repo that i could look at?

Hey sorry, It's a private repo, but you can let me know what all you want to have a look at, I'll mail those things to you.

**Comment by quicksilverr** [comment]
The error, is from the EAS website, in the EAS build section

**Comment by quicksilverr** [comment]
The major issue that I'm facing is the replacing of the "*" with the accurate package version before building the app in the eas build phase. Just to give an idea. 
I have a react nx monorepo, which uses react native and react native web. My current app, is a pure react native project. Which following the expo docs, have made the needed changes in the MainActivity and MainApplication.java, and have configured eas:build and eas:update , so the eas.json and app.json is added in the application. 

I have made use of the code from @nx/expo repo, and set up the eas update executor and that works properly. It's just this build phases that's turning out to be a major blocker. Manually changing the versions, everytime is too laborious.

**Comment by xiongemi** [comment]
@quicksilverr not sure I got what you meant. it sounds like your expo app is not a part of the nx monorepo? are using `eas:build` command directly?
if your expo app is a part of nx monorepo, why not use command `nx build <your expo app name>` at workspace root, not app root. you do not need to manually replace "*" in package.json. this is what tools/scripts/eas-build-pre-install.mjs will do it for you.

what version of @nx/expo are you using? did you run the migration script when you upgraded nx? `nx migrate latest` then `nx migrate --run-migrations`? if not, you might need to manually copy the https://github.com/xiongemi/nx-expo-monorepo/blob/main/tools/scripts/eas-build-pre-install.mjs and https://github.com/xiongemi/nx-expo-monorepo/blob/main/tools/scripts/eas-build-pre-install.mjs to your workspace's tools/scripts folder.

**Comment by quicksilverr** [comment]
Hey @xiongemi  with the local flag it works, but now how do you upload the local build to expo?
